DynamoDB:
  - "{ENV}.xxwmm.reference-data-record"

lambda:
  - lmb-euw1-{ENV}-cloudwatch-to-datadog-001

docker:
  - consolidated-daily-extract-controller

#Environments and corresponding credential ID
env:
  dev: TERRAFORM_SANDPIT_PEOPLE
  ops: TERRAFORM_SANDPIT_PEOPLE
  sit: JENKINS_NONPROD_PEOPLE
  uat: JENKINS_NONPROD_PEOPLE
  pre: JENKINS_NONPROD_PEOPLE
  prd: PEOPLE_TERRAFORM_PROD

#Read only environments
ro-env:
  - prd
  - ops

lambda_bucket:
  dev: mdev.lambda.kqtizgpble
  ops: mops.lambda.mkorngxkwq
  pre: mpre.lambda.ecblqihhzw
  sit: msit.lambda.lstqfstkrc
  uat: muat.lambda.fpflmyeckk
  prd: mprd.lambda.mudlyfnnhv

